/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppFormsRouteImport } from './routes/app.forms'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppContactsRouteImport } from './routes/app.contacts'
import { Route as AppBookingsRouteImport } from './routes/app.bookings'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAutomationsRouteImport } from './routes/app.automations'
import { Route as AppFormsFormIdRouteImport } from './routes/app.forms.$formId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsRoute = AppFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsFormIdRoute = AppFormsFormIdRouteImport.update({
  id: '/$formId',
  path: '/$formId',
  getParentRoute: () => AppFormsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/forms': typeof AppFormsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/forms/$formId': typeof AppFormsFormIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/forms': typeof AppFormsRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/forms/$formId': typeof AppFormsFormIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/forms': typeof AppFormsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/forms/$formId': typeof AppFormsFormIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/automations'
    | '/app/billing'
    | '/app/bookings'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/forms'
    | '/app/'
    | '/app/forms/$formId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/automations'
    | '/app/billing'
    | '/app/bookings'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/forms'
    | '/app'
    | '/app/forms/$formId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/automations'
    | '/app/billing'
    | '/app/bookings'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/forms'
    | '/app/'
    | '/app/forms/$formId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forms': {
      id: '/app/forms'
      path: '/forms'
      fullPath: '/app/forms'
      preLoaderRoute: typeof AppFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contacts': {
      id: '/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings': {
      id: '/app/bookings'
      path: '/bookings'
      fullPath: '/app/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automations': {
      id: '/app/automations'
      path: '/automations'
      fullPath: '/app/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forms/$formId': {
      id: '/app/forms/$formId'
      path: '/$formId'
      fullPath: '/app/forms/$formId'
      preLoaderRoute: typeof AppFormsFormIdRouteImport
      parentRoute: typeof AppFormsRoute
    }
  }
}

interface AppFormsRouteChildren {
  AppFormsFormIdRoute: typeof AppFormsFormIdRoute
}

const AppFormsRouteChildren: AppFormsRouteChildren = {
  AppFormsFormIdRoute: AppFormsFormIdRoute,
}

const AppFormsRouteWithChildren = AppFormsRoute._addFileChildren(
  AppFormsRouteChildren,
)

interface AppRouteChildren {
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBookingsRoute: typeof AppBookingsRoute
  AppContactsRoute: typeof AppContactsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFormsRoute: typeof AppFormsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAutomationsRoute: AppAutomationsRoute,
  AppBillingRoute: AppBillingRoute,
  AppBookingsRoute: AppBookingsRoute,
  AppContactsRoute: AppContactsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFormsRoute: AppFormsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
